[logging]
console_level = 'info'
file_level = 'debug'
file_path = './logs'

[s3]
# The maximum number of retry count
max_retry_count = 5
# The concurrency per generation job
per_job_concurrency = 4

[connection]
# Connection string to MongoDB, it can be either a built-in mongodb
# shipped with this software or a standalone mongodb server
database = "mongodb://127.0.0.1:37000"

# Connection string to deal preparation service, used by Singularity CLI
deal_preparation_service = 'http://127.0.0.1:7001'
deal_replication_service = 'http://127.0.0.1:7004'

# Connection string to index service, used by Singularity CLI
index_service = 'http://127.0.0.1:7003'

[deal_preparation_service]
enabled = true
# API to serve singularity prep commands
bind = "0.0.0.0"
port = 7001
minDealSizeRatio = 0.55
maxDealSizeRatio = 0.95
# Whether to cleanup temporary CAR files
enable_cleanup = true

[database]
# Start a built-in MongoDB server shipped with this software
start_local = true
# The path to store the MongoDB database
local_path = "./database"
# MongoDB API
local_bind = "0.0.0.0"
local_port = 37000

[deal_preparation_worker]
enabled = true
# Number of workers to start, one worker consumes 2 - 2.5 CPUs
num_workers = 4
# Buffer for child spawn
max_buffer = 1073741824

[index_service]
enabled = true
# API to serve singularity index commands
bind = "0.0.0.0"
port = 7003
# If not using the built-in IPFS daemon, use below URI to connect to IPFS API
ipfs_http = "http://localhost:5001"

[ipfs]
# Whether to start a built-in IPFS daemon - experimental
enabled = false

[http_hosting_service]
enabled = true
bind = "0.0.0.0"
port = 8088
static_path = "./cars"

[deal_tracking_service]
enabled = true
lotus_api = "https://api.node.glif.io/rpc/v0"
lotus_token = ""

[deal_replication_service]
enabled = true
bind = "0.0.0.0"
port = 7004

[deal_replication_worker]
enabled = true
min_retry_wait_ms = 30000
max_retry_count = 3
boost_cli_cmd = "boost" #if not in PATH, specify full location here
lotus_cli_cmd = "lotus" #if not in PATH, specify full location here
